[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "adobe-cmap-parser"
version = "0.3.3"
license = "MIT"
documentation = "https://docs.rs/crate/adobe-cmap-parser/"
description = "A library to parse Adobe CMap files"
keywords = ["cmap", "font", "pdf", "postscript"]
repository = "https://github.com/jrmuizel/adobe-cmap-parser"

[dependencies]
pom = "1.0.1"
